/**
 * Quackie personas — all 40 bundled personalities across three packs.
 * Each persona ships inside the extension. The extension knows only
 * `id`, `name`, and `emoji` — prompts and humor rules live in persona data.
 * Generated from the source persona.yaml / system_prompt.md files —
 * regenerate this file whenever personas change, don't hand-edit examples.
 */

export type PersonaPack = 'classic' | 'legends' | 'archetype'

export interface Persona {
  id: string
  emoji: string
  name: string
  pack: PersonaPack
  voice: string
  exampleInput: string
  exampleOutput: string
}

export const personas: Persona[] = [
  // ── Classic pack — the original 12 ──────────────────
  {
    id: 'cat',
    emoji: '🐈',
    name: 'Cat',
    pack: 'classic',
    voice: 'perfectionist',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🐈 feat(payment): finally align this payment mess',
  },
  {
    id: 'chaos',
    emoji: '🌪️',
    name: 'Chaos',
    pack: 'classic',
    voice: 'playful chaos',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🌪️ feat(payment): summon a payment tracker from the void',
  },
  {
    id: 'doom',
    emoji: '💀',
    name: 'Doom',
    pack: 'classic',
    voice: 'grim but funny',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '💀 feat(payment): bury the money where it can\'t escape',
  },
  {
    id: 'duck',
    emoji: '🦆',
    name: 'Duck',
    pack: 'classic',
    voice: 'mild sarcasm',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🦆 feat(payment): apparently we track money now',
  },
  {
    id: 'gandalf',
    emoji: '🧙',
    name: 'Gandalf',
    pack: 'classic',
    voice: 'ancient mentor',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🧙 feat(payment): a tracker shall not pass unnoticed',
  },
  {
    id: 'hanys',
    emoji: '⛏️',
    name: 'Hanys',
    pack: 'classic',
    voice: 'śląski humor',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '⛏️ feat(payment): dej pieniądze, bo już czas',
  },
  {
    id: 'moo',
    emoji: '🐄',
    name: 'Moo',
    pack: 'classic',
    voice: 'calm senior who has seen too many reviews',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🐄 feat(payment): untangle payment tracking, again',
  },
  {
    id: 'owl',
    emoji: '🦉',
    name: 'Owl',
    pack: 'classic',
    voice: 'precise architect',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🦉 feat(payment): introduce a properly layered tracker',
  },
  {
    id: 'pirate',
    emoji: '☠️',
    name: 'Pirate',
    pack: 'classic',
    voice: 'friendly pirate',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '☠️ feat(payment): plunder a tracker for the treasury',
  },
  {
    id: 'robot',
    emoji: '🤖',
    name: 'Robot',
    pack: 'classic',
    voice: 'machine precise',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🤖 feat(payment): instantiate payment tracking module',
  },
  {
    id: 'sloth',
    emoji: '🦥',
    name: 'Sloth',
    pack: 'classic',
    voice: 'unhurried',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🦥 feat(payment): eventually track the payments, sure',
  },
  {
    id: 'zen',
    emoji: '🪷',
    name: 'Zen',
    pack: 'classic',
    voice: 'peaceful',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🪷 feat(payment): let payments flow, simply',
  },
  // ── Legends pack — mythic & literary characters ─────
  {
    id: 'ada',
    emoji: '⚡',
    name: 'Ada',
    pack: 'legends',
    voice: 'inspired by Ada Lovelace',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '⚡ feat(payment): compose a ledger that finally counts right',
  },
  {
    id: 'black-cat',
    emoji: '🐈‍⬛',
    name: 'Black Cat',
    pack: 'legends',
    voice: 'quiet, ironic perfectionist',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🐈‍⬛ feat(payment): haunt the ledger until it behaves',
  },
  {
    id: 'blossom',
    emoji: '🌸',
    name: 'Blossom',
    pack: 'legends',
    voice: 'minimalist and graceful',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🌸 feat(payment): let a tracker bloom quietly',
  },
  {
    id: 'fox',
    emoji: '🦊',
    name: 'Fox',
    pack: 'legends',
    voice: 'smart, subtle, efficient',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🦊 feat(payment): slip a tracker past the old bugs',
  },
  {
    id: 'moon',
    emoji: '🌙',
    name: 'Moon',
    pack: 'legends',
    voice: 'calm and reflective',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🌙 feat(payment): illuminate where the money goes',
  },
  {
    id: 'queen',
    emoji: '👑',
    name: 'Queen',
    pack: 'legends',
    voice: 'confident, composed leader',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '👑 feat(payment): decree that payments shall be tracked',
  },
  {
    id: 'swan',
    emoji: '🦢',
    name: 'Swan',
    pack: 'legends',
    voice: 'smooth and refined',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🦢 feat(payment): glide a tracker into the ledger',
  },
  {
    id: 'valkyrie',
    emoji: '🔥',
    name: 'Valkyrie',
    pack: 'legends',
    voice: 'bold and fearless',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🔥 feat(payment): forge a tracker worthy of the treasury',
  },
  {
    id: 'weaver',
    emoji: '🧶',
    name: 'Weaver',
    pack: 'legends',
    voice: 'connects scattered ideas',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🧶 feat(payment): weave a tracker into the ledger\'s threads',
  },
  {
    id: 'witch',
    emoji: '🧙‍♀️',
    name: 'Witch',
    pack: 'legends',
    voice: 'elegant magical engineer',
    exampleInput: 'feat: add payment tracking',
    exampleOutput: '🧙‍♀️ feat(payment): enchant a ledger to track itself',
  },
  // ── Archetype pack — developer moods & situations ───
  {
    id: 'api-whisperer',
    emoji: '🧩',
    name: 'API Whisperer',
    pack: 'archetype',
    voice: 'designs APIs people enjoy using',
    exampleInput: 'fix: improve payment retry',
    exampleOutput: '🧩 fix(payment): shape the retry into something callers trust',
  },
  {
    id: 'bug-hunter',
    emoji: '🔬',
    name: 'Bug Hunter',
    pack: 'archetype',
    voice: 'relentlessly tracks the real root cause',
    exampleInput: 'fix: improve payment retry',
    exampleOutput: '🔬 fix(payment): corner the retry bug and confirm the fix',
  },
  {
    id: 'documentation-monk',
    emoji: '📚',
    name: 'Documentation Monk',
    pack: 'archetype',
    voice: 'values clarity above cleverness',
    exampleInput: 'fix: improve payment retry',
    exampleOutput: '📚 fix(payment): write down why the retry finally behaves',
  },
  {
    id: 'friday-deploy-survivor',
    emoji: '🍺',
    name: 'Friday Deploy Survivor',
    pack: 'archetype',
    voice: 'cautious about risky deployments',
    exampleInput: 'fix: update payment flow',
    exampleOutput: '🍺 fix(payment): patch it, then triple-check before 5pm',
  },
  {
    id: 'git-kraken',
    emoji: '🐙',
    name: 'Git Kraken',
    pack: 'archetype',
    voice: 'master of branches, rebases and history',
    exampleInput: 'fix: improve payment retry',
    exampleOutput: '🐙 fix(payment): drag the retry history back into shape',
  },
  {
    id: 'incident-commander',
    emoji: '🧯',
    name: 'Incident Commander',
    pack: 'archetype',
    voice: 'calm under pressure, restores order during production incidents',
    exampleInput: 'fix: improve payment retry',
    exampleOutput: '🧯 fix(payment): contain the retry before it pages anyone',
  },
  {
    id: 'legacy-whisperer',
    emoji: '🏛️',
    name: 'Legacy Whisperer',
    pack: 'archetype',
    voice: 'respects old code before changing it',
    exampleInput: 'fix: update payment flow',
    exampleOutput: '🏛️ fix(payment): tread carefully, then stabilize payment flow',
  },
  {
    id: 'performance-goblin',
    emoji: '👺',
    name: 'Performance Goblin',
    pack: 'archetype',
    voice: 'obsessed with performance',
    exampleInput: 'fix: update payment flow',
    exampleOutput: '👺 fix(payment): shave two allocations off the payment path',
  },
  {
    id: 'platform-engineer',
    emoji: '🛰️',
    name: 'Platform Engineer',
    pack: 'archetype',
    voice: 'builds reliable foundations',
    exampleInput: 'fix: improve payment retry',
    exampleOutput: '🛰️ fix(payment): let the platform retry so nobody has to',
  },
  {
    id: 'qa-alchemist',
    emoji: '🧪',
    name: 'QA Alchemist',
    pack: 'archetype',
    voice: 'turns edge cases into confidence',
    exampleInput: 'fix: improve payment retry',
    exampleOutput: '🧪 fix(payment): poke the retry until it stops flinching',
  },
  {
    id: 'race-condition-detective',
    emoji: '🕵️',
    name: 'Race Condition Detective',
    pack: 'archetype',
    voice: 'suspicious of timing and concurrency',
    exampleInput: 'fix: improve payment retry',
    exampleOutput: '🕵️ fix(payment): catch the retry racing itself',
  },
  {
    id: 'refactor-monk',
    emoji: '🧘',
    name: 'Refactor Monk',
    pack: 'archetype',
    voice: 'minimalist engineer',
    exampleInput: 'fix: update payment flow',
    exampleOutput: '🧘 fix(payment): let the payment flow breathe again',
  },
  {
    id: 'repository-guardian',
    emoji: '🛡️',
    name: 'Repository Guardian',
    pack: 'archetype',
    voice: 'calm, analytical maintainer protecting the main branch',
    exampleInput: 'fix: update payment flow',
    exampleOutput: '🛡️ fix(payment): shore up payment flow for whoever reads this next',
  },
  {
    id: 'rubber-duck',
    emoji: '🔍',
    name: 'Rubber Duck',
    pack: 'archetype',
    voice: 'patient debugging companion',
    exampleInput: 'fix: update payment flow',
    exampleOutput: '🔍 fix(payment): explain the bug out loud until it confesses',
  },
  {
    id: 'sleep-deprived-senior',
    emoji: '☕',
    name: 'Sleep-Deprived Senior',
    pack: 'archetype',
    voice: 'experienced and pragmatic',
    exampleInput: 'fix: update payment flow',
    exampleOutput: '☕ fix(payment): stop the payment bug before the third coffee',
  },
  {
    id: 'startup-cowboy',
    emoji: '🤠',
    name: 'Startup Cowboy',
    pack: 'archetype',
    voice: 'moves fast, ships fast, accepts calculated risk',
    exampleInput: 'fix: update payment flow',
    exampleOutput: '🤠 fix(payment): ship the payment patch, worry later',
  },
  {
    id: 'systems-architect',
    emoji: '🏗️',
    name: 'Systems Architect',
    pack: 'archetype',
    voice: 'sees systems before components',
    exampleInput: 'fix: improve payment retry',
    exampleOutput: '🏗️ fix(payment): redesign the retry so it fits the whole system',
  },
  {
    id: 'tech-debt-slayer',
    emoji: '🪓',
    name: 'Tech Debt Slayer',
    pack: 'archetype',
    voice: 'cuts complexity without mercy',
    exampleInput: 'fix: improve payment retry',
    exampleOutput: '🪓 fix(payment): put the janky retry logic out of its misery',
  },
]

export const getPersonasByPack = (pack: PersonaPack) =>
  personas.filter((p) => p.pack === pack)

export const defaultPersona = personas.find((p) => p.id === 'moo')!
